### ISSUE TITLE
WSL (Bash on Windows) issue with pages hanging forever with this plugin enabled

### ISSUE THREAD

**Issue by nickjj** [RobertDeRose/jekyll-livereload#12] opened 2017-10-15 13:14 UTC
Hi,

I've been using this plugin for a long time on a regular Linux based system and it's been awesome, totally flawless and thanks a lot for making it.

Recently I am trying to use WSL (Bash on Windows) which runs Ubuntu 16.x under the hood and Jekyll itself works ok even with inotify events and auto-regeneration.

However this plugin now causes all pages to hang forever. It will just result in a white screen with a permanent browser loading/busy icon.

Jekyll sees the changes and the livereload server runs but data just doesn't flow. The network tab in Chrome shows 0 responses, there's no errors in the console and I have no firewall running. Omitting the `--livereload` flag makes everything work as expected (but then no live reload of course).

##### Versions

```ruby
Chrome: 61 (latest stable)

gem 'jekyll', '~> 3.5'
gem 'jekyll-livereload', '~> 0.2'
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
```

**Comment by RobertDeRose** [comment] 2017-10-17 15:36
hmm... that sucks... I don't have a Windows machine to test this out on, but if I had to guess, I would have to assume that event machine is not compiling in a way that works on Windows so that something is blocking the process.

**Comment by nickjj** [comment] 2017-10-17 17:28
Microsoft is releasing a massive update today which has a ton of little fixes to WSL so maybe we'll get lucky and it'll work with that (I plan to update tonight and will report back how it goes).

But if not, is there anything I can do to help debug this (I have Ruby experience)? Your plugin is so good for writing blog posts and it would be a shame to lose this functionality.

**Comment by RobertDeRose** [comment] 2017-10-17 18:49
Let me know how it goes tonight, if you can't get it working, I will download a Microsoft VM and give it a go.  If you're blog source is public, link me or PM me it and I will try against your specific source to ensure it's not a unique issue if I can't reproduce with a basic Jekyll project

**Comment by nickjj** [comment] 2017-10-18 11:45
The same problem persists with the fall 2017 update of Windows 10.

But I did think of something since then. WSL is supposed to treat localhost normally. For example if Jekyll is running within WSL and is bound to 127.0.0.1 (which it is by default) and I open my browser from within Windows, I am able to access things at localhost.

As an experiment I set `-H 0.0.0.0` when I ran Jekyll and now at least requests come through with `--livereload` enabled but the live reload itself doesn't work (the browser doesn't reload).

However, now I think this problem isn't so much related to WSL directly because I had this same issue when I ran Jekyll through Docker (using Debian as a base image). Everything worked except live reload and ultimately it's the reason why I decided to run Jekyll without Docker on my dev box.

So with that said, I don't think you need a Windows box / VM to test this. All you have to do is run things through Docker and if you can get it working with an Alpine / Debian base Docker image you should be golden. Are you familiar with Docker? If not let me know and I can set you up with a sample project.

My blog isn't open source but I'm not doing anything too crazy. Here's some details:

##### Environment

```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
Chrome 62 (latest stable) on Windows 10 Pro
```

I had the same problem with Linux Chrome with my old set up when I had things Dockerized in a Linux VM.

##### Gemfile 

```ruby
source 'https://rubygems.org'
ruby RUBY_VERSION

gem 'jekyll', '~> 3.5'
gem 'bootstrap-sass', '~> 3.3'
gem 'font-awesome-sass', '~> 4.7'
gem 'uglifier', '~> 3.0'
gem 'twitter', '~> 5.11'

group :jekyll_plugins do
  gem 'jekyll-livereload', '~> 0.2'
  gem 'jekyll-paginate', '~> 1.1'
  gem 'jekyll-assets', '~> 2.3'
  gem 'jekyll-sitemap', '~> 0.11'
end
```

##### How I run Jekyll

`bundle exec jekyll serve --config "_config.yml,_config.dev.yml" --livereload --drafts`

I also use `--incremental` when I'm actively writing a post.

**Comment by RobertDeRose** [comment] 2017-10-19 14:12
@nickjj There is an issue with event machine https://github.com/eventmachine/eventmachine/issues/806

A possible workaround is to `do gem install eventmachine --platform ruby` for Ruby 2.4

**Comment by nickjj** [comment] 2017-10-19 14:16
Hmm, based on that issue that seems only related to Windows, but in this case Ruby is running on Ubuntu.

**Comment by nickjj** [comment] 2017-10-19 14:19
I did try it anyways but the result is the same. No requests come through, but `-H 0.0.0.0` lets them pass through however the browser never reloads on code change (but Jekyll reports the change in the terminal).

**Comment by RobertDeRose** [comment] 2017-10-19 14:31
And you can get Jekyll working without Livereload?  I wonder if it's just a port redirection issue, see when you run it locally, the default port is available, but with Docker and WSL, I would image you'd need to add something to tell it to allow the port to be redirected.  Docker I believe will do some automagical port detection and redirection, but not sure it handles multiple ports that way.   Let me see if I can get this working with Docker.

**Comment by nickjj** [comment] 2017-10-19 14:40
Correct, Jekyll is fully working. inotify works (no need for long polling), auto-regenerate works, incremental works, etc..

When it comes to WSL, published ports seem to just work on localhost. Jekyll is accessible on 4000, my custom Rails / Flask / etc. ports all work on their designated ports without doing any type of manual forwarding.

However, when I run Jekyll with `-H 0.0.0.0` I cannot visit `http://localhost:35729/livereload.js` directly. It times out. It also times out if I use a custom `-R 4001` port and try to access that so it's not some crazy high port issue.

It's also worth noting when I use `-H 0.0.0.0 -R 4001` your plugin is emiting this tag `<script src="http://0.0.0.0:4001/livereload.js"></script>` but all of my other Jekyll URLs are referencing `localhost` instead.

But, even with that said trying to manually access the `livereload.js` file with localhost still fails.

And for completion, even using `-H 192.168.1.2` fails with `--livereload` which is my WSL IP address. If I bind to that and leave out `--livereload` then I can access `192.168.1.2:4000` which is Jekyll.

**Edit**

With Docker, yep you'd want to run the container with `-p 4000:4000 -p 35729:35729` so both Jekyll and your plugin are accessible.

**Comment by RobertDeRose** [comment] 2017-10-19 15:30
Got a link or gist to your Dockerfile that you were using, would ensure I'm doing the same thing as you if you can

**Comment by nickjj** [comment] 2017-10-19 16:33
I just noticed I was using Ruby 2.3 in my old `Dockerfile` so it's not an isolated 2.4 thing either.

Here's an updated 2.4 Dockerfile:

```
FROM ruby:2.4-slim

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
      build-essential nodejs

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

ENV LC_ALL=C.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 JEKYLL_ENV=production

CMD jekyll build
```

Docker Compose file to run it:

```yml
version: '2'

services:
  nickjanetakis:
    build: .
    environment:
      - JEKYLL_ENV=development
    command: >
      jekyll serve
        --config _config.yml,_config.dev.yml
        --drafts --livereload
    ports:
      - '4000:4000'
      - '35729:35729'
    volumes:
      - '.:/app'
```

You would run it with `docker-compose up --build`.

**Comment by RobertDeRose** [comment] 2017-10-19 17:40
I'll give it a whirl as soon as I can.

**Comment by RobertDeRose** [comment] 2017-10-25 03:25
@nickjj Using the Dockerfile and docker-compose.yml files provided and with this simple Gemfile:

```ruby
source "https://rubygems.org"

gem 'jekyll', '~> 3.5'

group :jekyll_plugins do
  gem 'jekyll-livereload'
end
```

I am able to fully get Livereload to work.

I then tried your Gemfile listed above with the same result.  

I wish I could be of more help, perhaps it's something specific with your project?

**Comment by RobertDeRose** [comment] 2017-10-25 03:30
@nickjj just also an FYI, I tested Jekyll 3.6.2 as well, still no issues

**Comment by nickjj** [comment] 2017-10-25 11:47
That's interesting.

Would you be able to also test WSL in a Windows VM?

**Comment by RobertDeRose** [comment] 2017-10-25 19:33
Not anytime soon, but I will give it a try ASAP

**Comment by renzok** [comment] 2018-01-08 07:31
I had the same issue using Docker on Windows Version 17.09.1-ce-win42 (14687). I figured that the websocket was running on `0.0.0.0` inside the container. Although [`0.0.0.0` has several meanings](https://en.wikipedia.org/wiki/0.0.0.0) in most cases it indicates an error. However, within the internal network created by docker it seems to be of no importance as the internal ports on which the services are listening are all it really needs within the same container. 
However, `0.0.0.0` does definitely not work for web clients loading the livereload.js from jekyll server. Therefore calling jekyll with `-H 0.0.0.0` can not work properly. Hence my first attempt to configure  host for javascript URL differently than container internal (sometimes) failed host configuration.

**Comment by nickjj** [comment] 2018-01-20 18:44
That's what I've noticed too @renzok.

@RobertDeRose are you sure you were running Jekyll through Docker when you tested my above set up? I cannot reproduce it working inside of Docker.

For the record, even Phoenix's live reloading fails with Docker. Phoenix is a web framework that uses websocket driven / inotify based live code reloading.

**Comment by RobertDeRose** [comment] 2018-01-22 16:05
@nickjj yep, I'm positive I was able to get it to work, but then again, I am on Mac and you are on Windows, that might be the difference.  I've also use Phoenix before, but not through Docker, but I can give it a try today if I get a chance, doing some Docker stuff for work anyways.

**Comment by nickjj** [comment] 2018-01-22 16:36
I was able to get Phoenix to work in the end by setting `tty: true` on the service. I haven't tested that with a Dockerized Jekyll set up yet. I'm optimistic tho!

**Comment by RobertDeRose** [comment] 2021-03-18 13:36
Closing as this project is no longer maintained and the guts of it have been merged into Jekyll proper

**Closed as completed by RobertDeRose** 2021-03-18 13:36 UTC
