### ISSUE TITLE
Livereload not working with base_url

### ISSUE THREAD

**Issue by paulocesarpcfj** [RobertDeRose/jekyll-livereload#3] opened 2016-10-29 17:14 UTC
I'm getting this problem with Livereload. I have a base_url, and the livereload doesn't handle the path. How can I fix it?

```
[36mjekyll_1  |[0m Configuration file: /srv/jekyll/_config.yml
[36mjekyll_1  |[0m             Source: /srv/jekyll
[36mjekyll_1  |[0m        Destination: /srv/jekyll/_site
[36mjekyll_1  |[0m  Incremental build: disabled. Enable with --incremental
[36mjekyll_1  |[0m    Generating...
[36mjekyll_1  |[0m  done in 8.506 seconds.
[36mjekyll_1  |[0m  Auto-regeneration: enabled for '/srv/jekyll'
[36mjekyll_1  |[0m Configuration file: /srv/jekyll/_config.yml
[36mjekyll_1  |[0m  LiveReload Server: http://0.0.0.0:35729
[36mjekyll_1  |[0m Configuration file: /srv/jekyll/_config.yml
[36mjekyll_1  |[0m     Server address: http://0.0.0.0:4000/dulce/
[36mjekyll_1  |[0m   Server running... press ctrl-c to stop.
[36mjekyll_1  |[0m [2016-10-26 05:39:11] ERROR `/dulce/livereload.js' not found.
```

Thanks

**Comment by paulocesarpcfj** [comment] 2016-10-29 17:28
Also i'm getting this on console:

GET http://0.0.0.0:35729/livereload.js net::ERR_ADDRESS_INVALID

**Comment by RobertDeRose** [comment] 2016-10-30 00:53
@paulocesarpcfj can I get your configuration used to set a base_url? I need a way to reproduce the issue before I can solve it.  Also, GET issue seems weird, what console, your browsers' console?  That's a completely valid URL what platform (OS) are you using?

**Comment by RobertDeRose** [comment] 2016-10-30 01:05
@paulocesarpcfj I am unable to reproduce this, I added `baseurl` to my `_config.yml` and everything worked as expected.

**Comment by RobertDeRose** [comment] 2016-10-30 13:36
@paulocesarpcfj I'm going to close this is as not reproducible if you can't provide the steps to reproduce it in the next day. Thanks.

**Closed as completed** 2017-02-11 04:22 UTC
